/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hr.algebra.view;

import hr.algebra.dal.Repository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.model.Category;
import hr.algebra.model.JComponentInvisibleSettable;
import hr.algebra.utilities.MessageUtils;
import hr.algebra.view.model.CategoryTableModel;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.function.Predicate;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.ListSelectionModel;
import javax.swing.SpinnerListModel;
import javax.swing.table.TableColumn;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Derin
 */
public class EditCategoriesPanel extends javax.swing.JPanel implements JComponentInvisibleSettable {

    /**
     * Creates new form EditAuthorPanel
     */
    
    private CategoryTableModel model;
    
    public EditCategoriesPanel() {
        initComponents();
        init();
    }
    
    private List<JTextComponent> validationFields;
    private List<JLabel> errorLabels;

    private Repository repository;
    

    private Category selectedCategory;

    private void init() {
        try {
            initValidation();
            hideErrors(errorLabels);
            initRepository();
            initTable();
            clearForm();
//            initComponentShowListener();
            initSpinner();
            
        } catch (Exception ex) {
            Logger.getLogger(EditCategoriesPanel.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Unrecoverable error", "Cannot initiate the form");
            System.exit(1);
        }
    }

//    public void initComponentShowListener() {
//        //reload form on tab switch
//        addComponentListener(new ComponentAdapter() {
//            @Override
//            public void componentShown(ComponentEvent e) {
//                try {
//                    initTable();
//                } catch (Exception ex) {
//                    Logger.getLogger(EditAuthorsPanel.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpAddOrUpdate = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCategories = new javax.swing.JTable();
        btnRemoveCategory = new javax.swing.JButton();
        tfNewCategoryName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAddNewCategory = new javax.swing.JButton();
        lbCategoryNameError = new javax.swing.JLabel();
        rbUpdateCategory = new javax.swing.JRadioButton();
        rbAddNewCategory = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnRefresh = new javax.swing.JButton();
        spSpinner = new javax.swing.JSpinner();
        btnSetFilter = new javax.swing.JButton();
        btnClearFilter = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1341, 799));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tbCategories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCategoriesMouseClicked(evt);
            }
        });
        tbCategories.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbCategoriesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbCategories);

        btnRemoveCategory.setText("Remove");
        btnRemoveCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCategoryActionPerformed(evt);
            }
        });

        jLabel1.setText("Category name");

        jLabel2.setText("Add / update category");

        btnAddNewCategory.setText("Add / Update");
        btnAddNewCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCategoryActionPerformed(evt);
            }
        });

        lbCategoryNameError.setForeground(new java.awt.Color(153, 0, 0));
        lbCategoryNameError.setText("X");

        btngrpAddOrUpdate.add(rbUpdateCategory);
        rbUpdateCategory.setSelected(true);
        rbUpdateCategory.setText("Update");

        btngrpAddOrUpdate.add(rbAddNewCategory);
        rbAddNewCategory.setText("Add");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setMinimumSize(new java.awt.Dimension(10, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 10));

        btnRefresh.setText("Refresh table");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnSetFilter.setText("Filter");
        btnSetFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetFilterActionPerformed(evt);
            }
        });

        btnClearFilter.setText("Clear");
        btnClearFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(rbAddNewCategory)
                                .addGap(62, 62, 62)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(rbUpdateCategory)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbCategoryNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(984, 984, 984))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNewCategoryName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddNewCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(181, 181, 181)
                                .addComponent(btnRemoveCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefresh)
                                .addGap(112, 112, 112)
                                .addComponent(spSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSetFilter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClearFilter)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNewCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lbCategoryNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbAddNewCategory)
                        .addComponent(rbUpdateCategory))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewCategory)
                    .addComponent(btnRemoveCategory)
                    .addComponent(btnRefresh)
                    .addComponent(spSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetFilter)
                    .addComponent(btnClearFilter))
                .addGap(106, 106, 106))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCategoriesMouseClicked
        showCategory();
    }//GEN-LAST:event_tbCategoriesMouseClicked

    private void tbCategoriesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbCategoriesKeyReleased
        showCategory();
    }//GEN-LAST:event_tbCategoriesKeyReleased

    private void btnAddNewCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCategoryActionPerformed
        
        if (!formValid()) {
            return;
        }
        
        else {
            String categoryNameTf = tfNewCategoryName.getText().trim();
            if (rbUpdateCategory.isSelected()) {

                try {
                    repository.updateCategory(selectedCategory.getId(), new Category(categoryNameTf));
                } catch (Exception ex) {
                    Logger.getLogger(EditCategoriesPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if (rbAddNewCategory.isSelected()) {
                try {
                    repository.createCategory(new Category(categoryNameTf));
                } catch (Exception ex) {
                    Logger.getLogger(EditCategoriesPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            try {
                initTable();
            } catch (Exception ex) {
                Logger.getLogger(EditCategoriesPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAddNewCategoryActionPerformed

    private void btnRemoveCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCategoryActionPerformed
        if (selectedCategory == null) {
            MessageUtils.showInformationMessage("Information", "Select a category first");
        }
        
        try {
            
            //implement number of articles in use for a particular category
            int count = repository.selectCategoryArticleCount(selectedCategory.getId());
            
            if (count != 0) {
                MessageUtils.showErrorMessage("Category deletion failed", selectedCategory.getName() + " is currently in use by: " + count + " article(s)");
                return;
            }
            
            repository.deleteCategory(selectedCategory.getId());
            
            clearForm();
            initTable();
            
        } catch (Exception ex) {
            Logger.getLogger(EditCategoriesPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRemoveCategoryActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        try {
            initTable();
        } catch (Exception ex) {
            Logger.getLogger(EditCategoriesPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            initTable();
        } catch (Exception ex) {
            Logger.getLogger(EditCategoriesPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentShown

    private void btnSetFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetFilterActionPerformed
        var letterForFilter = spSpinner.getValue().toString().toUpperCase();
        Predicate<Category> letterFilter = category -> category.getName().toUpperCase().startsWith(letterForFilter);
        try {
            model = new CategoryTableModel(repository.selectCategories().stream().filter(letterFilter).collect(Collectors.toList()));
            updateTable();
        } catch (Exception ex) {
            Logger.getLogger(EditCategoriesPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSetFilterActionPerformed

    private void btnClearFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFilterActionPerformed
        try {
            initTable();
        } catch (Exception ex) {
            Logger.getLogger(EditCategoriesPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnClearFilterActionPerformed

    private boolean formValid() {
        hideErrors(errorLabels);
        boolean ok = true;

        for (int i = 0; i < validationFields.size(); i++) {
            ok &= !validationFields.get(i).getText().trim().isEmpty();
            errorLabels.get(i).setVisible(validationFields.get(i).getText().trim().isEmpty());
        }
        return ok;
    }
        
    public void showCategory() {
        int selectedRow = tbCategories.getSelectedRow();
        
        int rowId = tbCategories.convertRowIndexToModel(selectedRow);
        
        int id = (int) model.getValueAt(rowId, 0);
        
        Optional<Category> opt;
        try {
            
            opt = repository.selectCategory(id);
            if (opt.isPresent()) {
                selectedCategory = opt.get();
                fillForm(selectedCategory);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(EditCategoriesPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewCategory;
    private javax.swing.JButton btnClearFilter;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemoveCategory;
    private javax.swing.JButton btnSetFilter;
    private javax.swing.ButtonGroup btngrpAddOrUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbCategoryNameError;
    private javax.swing.JRadioButton rbAddNewCategory;
    private javax.swing.JRadioButton rbUpdateCategory;
    private javax.swing.JSpinner spSpinner;
    private javax.swing.JTable tbCategories;
    private javax.swing.JTextField tfNewCategoryName;
    // End of variables declaration//GEN-END:variables

    private void initValidation() {
        validationFields = Arrays.asList(tfNewCategoryName
        );
        errorLabels = Arrays.asList(lbCategoryNameError
        );
    }

    private void initRepository() {
        repository = RepositoryFactory.getInstance();
    }

    private void initTable() throws Exception {

        new Thread(() -> {
            try {
                model = new CategoryTableModel(repository.selectCategories());
                java.awt.EventQueue.invokeLater(() -> {
                    try {
                        tbCategories.setRowHeight(25);
                        tbCategories.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                        tbCategories.setAutoCreateRowSorter(true);
                        tbCategories.setModel(model);
                        TableColumn column0 = tbCategories.getColumnModel().getColumn(0);
                        column0.setPreferredWidth(50);
                        column0.setMinWidth(50);
                        column0.setMaxWidth(100);
                    } catch (Exception ex) {
                        Logger.getLogger(EditCategoriesPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                });
            } catch (Exception ex) {
                Logger.getLogger(EditCategoriesPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }).start();

    }
    

   private void clearForm() {
        hideErrors(errorLabels);
        validationFields.forEach(e -> e.setText(""));
        selectedCategory = null;
    }

    private void fillForm(Category selectedCategory) {
        if (rbUpdateCategory.isSelected()) {
            tfNewCategoryName.setText(selectedCategory.getName());
        }
    }

    private void initSpinner() {
        List<String> letters = IntStream.rangeClosed('A', 'Z')
                .mapToObj(c -> String.valueOf((char) c))
                .collect(Collectors.toList());
        spSpinner.setModel(new SpinnerListModel(letters));
        JSpinner.DefaultEditor editor = (JSpinner.DefaultEditor) spSpinner.getEditor();
        editor.getTextField().setEditable(false);
    }

    private void updateTable() {
                        tbCategories.setRowHeight(25);
                        tbCategories.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                        tbCategories.setAutoCreateRowSorter(true);
                        tbCategories.setModel(model);
                        TableColumn column0 = tbCategories.getColumnModel().getColumn(0);
                        column0.setPreferredWidth(50);
                        column0.setMinWidth(50);
                        column0.setMaxWidth(100);
    }

}
