/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hr.algebra.view;

import hr.algebra.dal.Repository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.dal.ValueStorageSingleton;
import hr.algebra.model.Article;
import hr.algebra.model.ThreadStatic;
import hr.algebra.model.ValueStorage;
import hr.algebra.parsers.rss.ArticleParser;
import hr.algebra.utilities.DerinUtils;
import hr.algebra.utilities.MessageUtils;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JMenu;

/**
 *
 * @author daniel.bele
 */
public class UploadArticlesPanel extends javax.swing.JPanel {

    /**
     * Creates new form UploadArticlesPanel
     */
    
    ValueStorage valueStorage;
    JMenu status;
    
    public UploadArticlesPanel(JMenu statusJMenu) {
        initComponents();
        initValueStorage();
        this.status = statusJMenu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lsArticles = new javax.swing.JList<>();
        btnUploadArticles = new javax.swing.JButton();
        btnDeleteArticles = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jScrollPane1.setViewportView(lsArticles);

        btnUploadArticles.setText("Download and append articles to repository");
        btnUploadArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadArticlesActionPerformed(evt);
            }
        });

        btnDeleteArticles.setText("Delete all articles and images");
        btnDeleteArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteArticlesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeleteArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUploadArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnDeleteArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUploadArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadArticlesActionPerformed
        
        try {
            //show program status in debug, thread working
            Logger.getLogger(UploadArticlesPanel.class.getName()).log(Level.INFO, ThreadStatic.getThreadStatusString().apply(valueStorage).get());
            
            valueStorage.changeThreadWorkStatus();
            DerinUtils.setStatusMenuBar(status, ThreadStatic.getThreadStatusString().apply(valueStorage).get());

            new Thread(() -> {
                try {
                    
                    //function
                    Logger.getLogger(UploadArticlesPanel.class.getName()).log(Level.INFO, ThreadStatic.getThreadStatusString().apply(valueStorage).get());
                    
                    
                    List<Article> articles = ArticleParser.parse();
                    repository.createArticles(articles);
                    java.awt.EventQueue.invokeLater(() -> {
                        try {
                            loadModel();
                            valueStorage.changeThreadWorkStatus();
                             DerinUtils.setStatusMenuBar(status, ThreadStatic.getThreadStatusString().apply(valueStorage).get());
                            Logger.getLogger(UploadArticlesPanel.class.getName()).log(Level.INFO, ThreadStatic.getThreadStatusString().apply(valueStorage).get());
                        } catch (Exception ex) {
                            Logger.getLogger(UploadArticlesPanel.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    });
                } catch (Exception ex) {
                    Logger.getLogger(UploadArticlesPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }).start();
            
        } catch (Exception ex) {
            MessageUtils.showErrorMessage("Unrecoverable error", "Unable to upload articles" + "\n Exception:" + ex.getMessage().toString());
            System.exit(1);
        }
    }//GEN-LAST:event_btnUploadArticlesActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        init();
    }//GEN-LAST:event_formComponentShown

    private void btnDeleteArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteArticlesActionPerformed
        
        if(!MessageUtils.showConfirmDialog("Delete database data", "Are you sure you want to delete all database data and images?")) {
            return;
        }
        
        //must init for if statement, arraylist so access is faster
        List<Article> allArticles = new ArrayList<Article>();
        
        try {
            allArticles = repository.selectArticles();
        } catch (Exception ex) {
            Logger.getLogger(UploadArticlesPanel.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Error", "Articles can not be retrieved from repository. Closing program" + ex.getMessage().toString());
            System.exit(1);
        }
        
        //yes but no, while empty, if the list is legitimately empty, this can wrongly close the program. --fixed
        if (allArticles.isEmpty()) {
            MessageUtils.showInformationMessage("Information", "The database is already empty.");
        }
        else {

            for (Article article : allArticles) {
                try {
                    if (article.getPicturePath() != null) {
                        Files.deleteIfExists(Paths.get(article.getPicturePath()));
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

            try {
                repository.deleteAll();
                MessageUtils.showInformationMessage("Deletion complete", "All database data and images have been successfull deleted!");
                loadModel();

            } catch (Exception ex) {
                Logger.getLogger(UploadArticlesPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnDeleteArticlesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteArticles;
    private javax.swing.JButton btnUploadArticles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Article> lsArticles;
    // End of variables declaration//GEN-END:variables

    private DefaultListModel<Article> articlesModel;
    private Repository repository;

    private void init() {
        try {
            repository = RepositoryFactory.getInstance();
            articlesModel = new DefaultListModel<>();
            loadModel();
        } catch (Exception ex) {
            Logger.getLogger(UploadArticlesPanel.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Unrecoverable error", "Cannot initiate the form");
            System.exit(1);
        }
    }
    
    private void loadModel() throws Exception {

        new Thread(() -> {
            try {
                List<Article> articles = repository.selectArticles();
                java.awt.EventQueue.invokeLater(() -> {
                    articlesModel.clear();
                    articles.forEach(articlesModel::addElement);
                    lsArticles.setModel(articlesModel);
                });
            } catch (Exception ex) {
                Logger.getLogger(EditArticlesPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }).start();
    }

    private void initValueStorage() {
        valueStorage = ValueStorageSingleton.getInstance();
    }

}
